# Intro to Bayesian Statistics Lab

Complete the following set of exercises to solidify your knowledge of Bayesian statistics and Bayesian data analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1. Cookie Problem

Suppose we have two bowls of cookies. Bowl 1 contains 30 vanilla cookies and 10 chocolate cookies. Bowl 2 contains 20 of each. You randomly pick one cookie out of one of the bowls, and it is vanilla. Use Bayes Theorem to calculate the probability that the vanilla cookie you picked came from Bowl 1?

In [2]:
def bayes_rule(priors,likelihood):
    marg=sum(np.multiply(priors,likelihood))
    post=np.divide(np.multiply(priors,likelihood),marg)
    return post

In [4]:
probas= [1/2,1/2]   #equal proba of picked from each bowl
likelihood=[0.75,0.5]   # proba of vanilla candy in each bowl
bayes_rule(probas,likelihood)[0]

0.6

What is the probability that it came from Bowl 2?

In [5]:
probas= [1/2,1/2]   #equal proba of picked from each bowl
likelihood=[0.75,0.5]   # proba of vanilla candy in each bowl
bayes_rule(probas,likelihood)[1]

0.4

What if the cookie you had picked was chocolate? What are the probabilities that the chocolate cookie came from Bowl 1 and Bowl 2 respectively?

In [6]:
probas= [1/2,1/2]   #equal proba of picked from each bowl
likelihood=[0.25,0.5]   # proba of vanilla candy in each bowl
bayes_rule(probas,likelihood)

array([0.33333333, 0.66666667])

## 2. Candy Problem

Suppose you have two bags of candies:

- In Bag 1, the mix of colors is:
    - Brown - 30%
    - Yellow - 20%
    - Red - 20%
    - Green - 10%
    - Orange - 10%
    - Tan - 10%
    
- In Bag 2, the mix of colors is:
    - Blue - 24%
    - Green - 20%
    - Orange - 16%
    - Yellow - 14%
    - Red - 13%
    - Brown - 13%
    
Not knowing which bag is which, you randomly draw one candy from each bag. One is yellow and one is green. What is the probability that the yellow one came from the Bag 1?

*Hint: For the likelihoods, you will need to multiply the probabilities of drawing yellow from one bag and green from the other bag and vice versa.*

In [8]:
probas= [1/2,1/2]   #equal proba of picked from each bag
likelihood=[0.2,0.14]   # proba of yellow candy in each bag

bayes_rule(probas,likelihood)[0]

0.5882352941176471

In [18]:
# taking into account we picked a yellow and green

priori = [1/2,1/2]
likelihood=[0.2*0.2,0.1*0.14]
bayes_rule(priori, likelihood)

array([0.74074074, 0.25925926])

What is the probability that the yellow candy came from Bag 2?

In [9]:
bayes_rule(probas,likelihood)[1]

0.411764705882353

What are the probabilities that the green one came from Bag 1 and Bag 2 respectively?

In [10]:
probas= [1/2,1/2]   #equal proba of picked from each bag
likelihood=[0.1,0.2]   # proba of yellow candy in each bag

bayes_rule(probas,likelihood)

array([0.33333333, 0.66666667])

In [19]:
## same as above
priori = [1/2,1/2]
likelihood=[0.1*0.14,0.2*0.2]
bayes_rule(priori, likelihood)

array([0.25925926, 0.74074074])

## 3. Monty Hall Problem

Suppose you are a contestant on the popular game show *Let's Make a Deal*. The host of the show (Monty Hall) presents you with three doors - Door A, Door B, and Door C. He tells you that there is a sports car behind one of them and if you choose the correct one, you win the car!

You select Door A, but then Monty makes things a little more interesting. He opens Door B to reveal that there is no sports car behind it and asks you if you would like to stick with your choice of Door A or switch your choice to Door C. Given this new information, what are the probabilities of you winning the car if you stick with Door A versus if you switch to Door C?

In [12]:
probas= [1/2,1/2]   #equal proba of picked from each bag
likelihood=[1/3,2/3]   # proba of yellow candy in each bag

bayes_rule(probas,likelihood)

array([0.33333333, 0.66666667])

## 4. Bayesian Analysis 

Suppose you work for a landscaping company, and they want to advertise their service online. They create an ad and sit back waiting for the money to roll in. On the first day, the ad sends 100 visitors to the site and 14 of them sign up for landscaping services. Create a generative model to come up with the posterior distribution and produce a visualization of what the posterior distribution would look like given the observed data.

In [13]:
observed = 14

def generative_model(param):
    result=np.random.binomial(100,param)
    return result



Produce a set of descriptive statistics for the posterior distribution.

In [14]:
n_draws=100000
prior = pd.Series(np.random.uniform(0,1,n_draws))

sim_data=[]
for p in prior:
    sim_data.append(generative_model(p))
    
posterior = prior[list(map(lambda x : x==observed, sim_data))]
#everytime we have 14 people registered

What is the 90% credible interval range?

In [15]:
print(posterior.quantile(.05), '|' ,posterior.quantile(.95))

0.09175898546250455 | 0.20580797429133987


What is the Maximum Likelihood Estimate?

In [16]:
rounded = posterior.round(2) #continuous variable, so has billions of poss, we need to round it
mode= rounded.mode()[0]

probability = list(rounded).count(mode)/len(rounded)
print('MLE = ',mode,'|',probability)



MLE =  0.15 | 0.12056737588652482
